# SIMPLIFIED GITOPS PATHS - Operator
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n4k-operator
  namespace: nirmata
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/n4k-deploy.git
    targetRevision: main
    path: nirmata-kyverno-operator  # SIMPLIFIED PATH!
    helm:
      releaseName: n4k-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: nirmata-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# SIMPLIFIED GITOPS PATHS - Kyverno  
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: nirmata
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/n4k-deploy.git
    targetRevision: main
    path: kyverno  # SIMPLIFIED PATH!
    helm:
      releaseName: kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
