# GitOps Application for N4K Kyverno 3.3.34
# Exact version you requested with fixes

apiVersion: argoproj.io/v1alpha1
kind: Application  
metadata:
  name: kyverno-n4k
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/n4k-deploy.git
    targetRevision: helm-repo-support-ok
    path: kyverno  # CORRECT path - no double slashes
    helm:
      releaseName: kyverno  # FIXES: missing release name error
      valueFiles:
        - values-public.yaml
      # Override values if needed
      values: |
        global:
          imagePullSecrets: []
        replicaCount: 1
        features:
          policyExceptions:
            enabled: true
            
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true  # Handle CRD updates

---
# Alternative: Packaged chart approach
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-n4k-packaged
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nirmata/n4k-deploy.git
    targetRevision: helm-repo-support-ok
    chart: kyverno
    helm:
      releaseName: kyverno
      version: "3.3.34"  # Your exact requested version
      values: |
        # N4K Kyverno v1.13.6-n4k.nirmata.10 configuration
        global:
          imagePullSecrets: []
        admissionController:
          replicas: 1
          imagePullSecrets: []
        backgroundController:
          replicas: 1
          imagePullSecrets: []  
        cleanupController:
          replicas: 1
          imagePullSecrets: []
        reportsController:
          replicas: 1
          imagePullSecrets: []
        features:
          policyExceptions:
            enabled: true
            
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
