# Nirmata Kyverno Operator 0.8.8 configuration for PUBLIC images
# Version: v0.4.13

# Use public GHCR images (no authentication required)
image:
  repository: ghcr.io/nirmata/nirmata-kyverno-operator
  tag: ~  # Uses chart appVersion v0.4.13
  pullPolicy: IfNotPresent
  pullSecrets:
    registry: ghcr.io
    name: ""  # No secret needed for public images
    create: false  # Don't create any pull secrets

# Standard settings for testing
replicaCount: 1
profile: "prod"

# Kyverno component settings for N4K 3.3.34
kyverno:
  createCR: true
  enablePolicyExceptions: true
  
  # Reduced replicas for demo/testing
  admissionController:
    replicas: 1
    
  backgroundController:
    replicas: 1
    
  cleanupController:
    replicas: 1
    
  reportsController:
    replicas: 1

# Webhook and security settings
enableWebhook: true
secureOperator: true
kyvernoNamespace: kyverno
certManager: operator

# No license secrets for public demo
apiAndLicenseSecretExists: false

# Basic RBAC settings
rbac:
  create: true
  serviceAccount:
    create: true
