# N4K Values file for GHCR deployment - Fixed structure

# Policy Exceptions Configuration
features:
  policyExceptions:
    namespace: "*"
    enabled: true

# Global Configuration
global:
  # Global image pull secrets
  imagePullSecrets:
    - name: ghcr-secret
  
  # Disable global registry to avoid path conflicts
  image:
    registry: ~

# Admission Controller Configuration
admissionController:
  image:
    registry: ~
    defaultRegistry: ~
    repository: ghcr.io/vikashkaushik01/kyverno
    tag: v1.13.6-n4k.nirmata.10
    pullPolicy: IfNotPresent
  
  initContainer:
    image:
      registry: ~
      defaultRegistry: ~
      repository: ghcr.io/vikashkaushik01/kyvernopre
      tag: v1.13.6-n4k.nirmata.10
      pullPolicy: IfNotPresent

# Background Controller Configuration  
backgroundController:
  image:
    registry: ~
    defaultRegistry: ~
    repository: ghcr.io/vikashkaushik01/background-controller
    tag: v1.13.6-n4k.nirmata.10
    pullPolicy: IfNotPresent

# Cleanup Controller Configuration
cleanupController:
  image:
    registry: ~
    defaultRegistry: ~
    repository: ghcr.io/vikashkaushik01/cleanup-controller
    tag: v1.13.6-n4k.nirmata.10
    pullPolicy: IfNotPresent

# Reports Controller Configuration
reportsController:
  image:
    registry: ~
    defaultRegistry: ~
    repository: ghcr.io/vikashkaushik01/reports-controller
    tag: v1.13.6-n4k.nirmata.10
    pullPolicy: IfNotPresent

# CLI Image Configuration (used in hooks)
cli:
  image:
    registry: ~
    defaultRegistry: ~
    repository: ghcr.io/vikashkaushik01/kyverno-cli
    tag: v1.13.6-n4k.nirmata.10
    pullPolicy: IfNotPresent

# Test Configuration
test:
  image:
    registry: ~
    repository: ghcr.io/vikashkaushik01/busybox
    tag: "1.35"
    pullPolicy: IfNotPresent

# Hooks Configuration
hooks:
  image:
    registry: ~
    repository: ghcr.io/vikashkaushik01/kubectl
    tag: "1.32.1"
    pullPolicy: IfNotPresent

# Image Pull Secrets (removed - using global instead)
